plugins { id 'java' }
import javax.inject.Inject
interface Injected { @Inject ExecOperations getExecOperations() }

group = 'dev.jojofr.multicrafter'
version = '1.5.2'

def mindustryVersion = 'v159'
def mindustryGameVersion = 'v159.7'

java {
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()

    //Downloads the server-release JAR file from Mindustry releases; does not use any real repository. Surprisingly, this is the most reliable option.
    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact(
                (mindustryVersion == 'latest' ? '/[organisation]/[module]/releases/[revision]/download/dependencies.jar' : // Latest stable release
                mindustryVersion == 'be' ? '/[organisation]/[module]/releases/download/master/[revision].jar' : // Latest BE build
                '/[organisation]/[module]/releases/download/[revision]/dependencies.jar')) // Specific release
        }
        metadataSources { artifact() }

        content {
            if (mindustryVersion == 'be') includeVersion("Anuken", "MindustryBuilds", "latest")
            else includeVersion("Anuken", "Mindustry", mindustryVersion)
        }
    }

    maven { url = 'https://jitpack.io' }
}

sourceSets {
    testMod {
        java.srcDirs = ['src/testMod/java']
        resources.srcDirs = ['src/testMod/resources']
    }
}

dependencies {
    compileOnly mindustryVersion == 'be' ? 'Anuken:MindustryBuilds:latest' : "Anuken:Mindustry:$mindustryVersion"

    compileOnly 'com.github.EB-wilson:TooManyItems:3.2'

    testModImplementation sourceSets.main.output
    testModCompileOnly mindustryVersion == 'be' ? 'Anuken:MindustryBuilds:latest' : "Anuken:Mindustry:$mindustryVersion"
}


jar {
    archiveFileName = "${project.name}Desktop.jar"

    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    from (layout.projectDirectory.files('mod.json', 'mod.hjson', 'icon.png'))
}

tasks.register('jarAndroid') {
    dependsOn jar

    // Configuration cache compatible
    def compileClasspath = configurations.compileClasspath
    def runtimeClasspath = configurations.runtimeClasspath

    def desktopJarFile = layout.buildDirectory.file("libs/${project.name}Desktop.jar")
    def androidJarFile = layout.buildDirectory.file("libs/${project.name}Android.jar")

    def sdkRoot = providers.environmentVariable('ANDROID_HOME').orElse(providers.environmentVariable('ANDROID_SDK_ROOT')).orNull
    def isWindows = providers.systemProperty('os.name').get().toLowerCase().contains('win')

    inputs.files(compileClasspath, runtimeClasspath, desktopJarFile)
    outputs.file(androidJarFile)

    def injected = objects.newInstance(Injected)
    doLast {
        if(!sdkRoot || !new File(sdkRoot).exists()) throw new GradleException('No valid Android SDK found. Ensure that ANDROID_HOME is set to your Android SDK directory.')

        def platformRoot = new File("$sdkRoot/platforms/").listFiles()?.sort()?.reverse()?.find{ f -> new File(f, 'android.jar').exists() }
        if(!platformRoot) throw new GradleException('No android.jar found. Ensure that you have an Android platform installed.')

        // Collect dependencies needed for desugaring
        def dependencies = (compileClasspath.asList() + runtimeClasspath.asList() + [new File(platformRoot, 'android.jar')])
                .collectMany{ ['--classpath', it.path] }

        // Dex and desugar files - this requires d8 in your PATH
        injected.execOperations.exec {
            commandLine isWindows ? 'd8.bat' : 'd8'
            args dependencies
            args '--min-api', '14', '--output', androidJarFile.get().asFile.absolutePath, desktopJarFile.get().asFile.absolutePath

            workingDir new File('build/libs')
            standardOutput = System.out
            errorOutput = System.err
        }
    }
}

tasks.register('deploy', Jar) {
    dependsOn jarAndroid
    dependsOn jar
    archiveFileName = "${project.name}.jar"

    def desktopJarFile = layout.buildDirectory.file("libs/${project.name}Desktop.jar")
    def androidJarFile = layout.buildDirectory.file("libs/${project.name}Android.jar")

    from(desktopJarFile.map { zipTree(it) })
    from(androidJarFile.map { zipTree(it) })
}


tasks.register('jarTest', Jar) {
    archiveFileName = "${project.name}-test.jar"
    from sourceSets.testMod.output
}

def gameFile = layout.projectDirectory.file('run/Mindustry.jar')
def gameDataDir = layout.projectDirectory.dir('run/data')

tasks.register('downloadGame') {
    outputs.file(gameFile)

    doLast {
        def url = "https://github.com/Anuken/Mindustry/releases/download/${mindustryGameVersion}/Mindustry.jar"
        def targetFile = gameFile.asFile
        targetFile.parentFile.mkdirs()

        URI.create(url).toURL().withInputStream { input ->
            targetFile.withOutputStream { output ->
                output << input
            }
        }
    }
}

tasks.register('copyLibToMods', Copy) {
    def renamedJar = "${project.name}.jar"
    from jar into gameDataDir.dir('mods') rename { renamedJar }
}

tasks.register('copyTestToMods', Copy) {
    dependsOn jarTest
    def renamedJar = "${project.name}-test.jar"
    from jarTest into gameDataDir.dir('mods') rename { renamedJar }
}

tasks.register('removeMods', Delete) {
    delete gameDataDir.file("mods/${project.name}.jar")
    delete gameDataDir.file("mods/${project.name}-test.jar")
}

tasks.register('run', JavaExec) {
    dependsOn 'downloadGame'
    dependsOn 'copyLibToMods'
    dependsOn 'copyTestToMods'

    environment 'MINDUSTRY_DATA_DIR', gameDataDir.asFile.absolutePath
    mainClass = '-jar'
    args = [gameFile.asFile.absolutePath]
}

tasks.register('runMobile', JavaExec) {
    dependsOn 'downloadGame'
    dependsOn 'copyLibToMods'
    dependsOn 'copyTestMod'

    environment 'MINDUSTRY_DATA_DIR', gameDataDir.asFile.absolutePath
    mainClass = '-jar'
    args = [gameFile.asFile.absolutePath, '-testMobile']
}

tasks.register('runNoMod', JavaExec) {
    dependsOn 'downloadGame', 'removeMods'

    environment 'MINDUSTRY_DATA_DIR', gameDataDir.asFile.absolutePath
    mainClass = '-jar'
    args = [gameFile.asFile.absolutePath]
}
